language: go

services:
  - docker

before_install:
  - docker build --no-cache -t mauricethomas/wgnw:${TRAVIS_COMMIT} .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mauricethomas/wgnw:${TRAVIS_COMMIT}