apiVersion: v1
kind: Service
metadata:
  name: {{ include "wgnw.fullname" . }}
  labels:
{{ include "wgnw.labels" . | indent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '{{ .Values.service.metrics }}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.metrics }}
      targetPort: exporter
      protocol: TCP
      name: exporter
  selector:
    app.kubernetes.io/name: {{ include "wgnw.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
